namespace: user1-reverse-words-stage
commonLabels:
  app: reversewords-stage
bases:
- github.com/tgubeli/reverse-words-cicd?ref=config
resources:
- namespace.yaml
- ingress.yaml
patchesStrategicMerge:
- deployment.yaml
